version: '3'

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kongpass
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"

  kong-migrations:
    container_name: kong-migrations
    image: kong/kong-gateway:2.8.1.0-alpine
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kongpass
      - KONG_PASSWORD=test
    command: kong migrations bootstrap
    # command: kong migrations up
    # command: kong migrations finish
    restart: on-failure
    depends_on:
      - kong-database
  kong:
    build:
        context: ./ 
    # image: kong/kong-gateway:2.8.1.0-alpine
    container_name: kong
    privileged: true
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kongpass
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_URL=http://0.0.0.0:8002
    restart: on-failure
    ports:
    - 8000:8000
    - 8443:8443
    - 8001:8001
    - 8444:8444
    - 8002:8002
    - 8445:8445
    - 8003:8003
    - 8004:8004
    links:
      - kong-database:kong-database
    depends_on:
      - kong-migrations

  # deck:
  #   image: kong/deck
  #   container_name: deck
  #   entrypoint: deck ping
  #   entrypoint: deck dump -o /mnt/deck/kong.yaml
  #   entrypoint: deck sync -s /mnt/deck/kong.yaml
  #   environment:
  #     DECK_KONG_ADDR: http://kong:8001
  #   depends_on:
  #     - kong
  #   volumes:
  #     - ${PWD}/config/:/mnt/deck/

  konga-database:
    image: postgres:9.6
    container_name: konga-database
    ports:
      - 5050:5432
    environment:
      - POSTGRES_USER=konga
      - POSTGRES_DB=konga
      - POSTGRES_PASSWORD=kongapass
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"

  konga:
    image: pantsel/konga
    ports:
      - 1337:1337
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=production
volumes:
  db-data-kong-postgres:
